//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pogress_gymEntities : DbContext
    {
        public Pogress_gymEntities()
            : base("name=Pogress_gymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Forma_Pago> tbl_Forma_Pago { get; set; }
        public virtual DbSet<tbl_IngresosXCliente> tbl_IngresosXCliente { get; set; }
        public virtual DbSet<tbl_Plan> tbl_Plan { get; set; }
        public virtual DbSet<tbl_pro_Clientes> tbl_pro_Clientes { get; set; }
        public virtual DbSet<tbl_pro_Usuarios> tbl_pro_Usuarios { get; set; }
        public virtual DbSet<tbl_LOG_IngresosXCliente> tbl_LOG_IngresosXCliente { get; set; }
        public virtual DbSet<tbl_Ventas> tbl_Ventas { get; set; }
        public virtual DbSet<tbl_ventas_clientes> tbl_ventas_clientes { get; set; }
        public virtual DbSet<tbl_Conceptos> tbl_Conceptos { get; set; }
        public virtual DbSet<tbl_DeudasXCliente> tbl_DeudasXCliente { get; set; }
        public virtual DbSet<tbl_LogRegistroClientes> tbl_LogRegistroClientes { get; set; }
    }
}
