//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ventas
    {
        public int Id_Venta { get; set; }
        public int Id_Usuario { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public int Id_Concepto { get; set; }
        public int Valor_Venta { get; set; }
        public string Hora_Venta { get; set; }
        public Nullable<int> Id_Forma_pago { get; set; }
        public string NameCliente { get; set; }
    }
}
