//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pro_Clientes
    {
        public int Id_Cliente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_nacimiento { get; set; }
        public string Documento_identitdad { get; set; }
        public string Celular { get; set; }
        public int Id_Plan { get; set; }
        public int Id_Forma_pago { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Fecha_registro { get; set; }
        public int Id_Usuario { get; set; }
        public System.DateTime Fecha_inicio { get; set; }
        public System.DateTime Fecha_fin { get; set; }
        public System.DateTime Fecha_Actualizacion { get; set; }
    }
}
