//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeudasXCliente
    {
        public int Id_Deuda { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Cliente { get; set; }
        public System.DateTime Fecha_deuda { get; set; }
        public string Hora_deuda { get; set; }
        public string descripcion { get; set; }
        public int Valor_deuda { get; set; }
    }
}
