//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ventas_clientes
    {
        public int Id_Ventas_Cliente { get; set; }
        public int Id_Plan { get; set; }
        public int Valor_Venta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora_Venta_Cliente { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
    }
}
